CREATE DATABASE vividtheory;

CREATE TABLE blogs(
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	slug VARCHAR(255) UNIQUE NOT NULL,
	content TEXT,
	image VARCHAR(255),
	published_at DATE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP
);  