CREATE DATABASE vividtheory;

DROP TABLE IF EXISTS blogs;

CREATE TABLE blogs(
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	slug TEXT UNIQUE NOT NULL,
	content TEXT,
	image VARCHAR(255),
	published_at DATE,
	created_at TIMESTAMP NOT NULL DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'yyyy-mm-dd HH24:MI:SS'),
	updated_at TIMESTAMP NOT NULL DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'yyyy-mm-dd HH24:MI:SS'),
	deleted_at TIMESTAMP
);  